tasks:
- init: pip3 install cfn-lint pydot && cfn-lint --update-iam-policies && cfn-lint --update-specs && gem install cfn-nag
vscode:
  extensions:
    - kddejong.vscode-cfn-lint@0.15.1:50PbpkKWNaGBTSqy8c0kBg==
